# Generated by Django 4.1.7 on 2023-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='IMAGE'),
        ),
    ]
