# Generated by Django 4.1.7 on 2023-03-04 04:44

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(verbose_name='CONTENT'),
        ),
    ]
