# Generated by Django 4.1.7 on 2023-03-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='900x400.png', upload_to='blog/%Y/%m/', verbose_name='IMAGE'),
        ),
    ]
