version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 774
    type:
      - directory
      - file
files:
  - source: ./backend/
    destination: /home/ubuntu/backend
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
  AfterInstall:
    - location: scripts/afterInstall.sh
