name: Backend Deploy # action 명

on: # 이벤트 트리거
  push: # push event에 반응
    paths:
      - "backend/**" # backend의 변경이 있을 때
    branches: # github repository의 branch가 
      - main # main 일 경우만

jobs: 
 deploy: # GitHub-hosted runners env
    runs-on: ubuntu-latest # using Ubuntu

    defaults:
      run:
        working-directory: "backend" # backend 폴더에서 실행

    steps:
      - uses: actions/checkout@v3
      
      - name: Create CodeDeploy Deployment
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_REGION }}'
        run: |
          aws deploy create-deployment \
            --application-name DjangoToEC2Deploy \
            --deployment-group-name autoDeployGroup \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --file-exists-behavior OVERWRITE \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}