name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * MON' # 월요일 세계시 기준 0시에 실행 https://crontab.guru

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "frontend" # frontend 폴더에서 실행

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Generate sitemap
        run: node scripts/generate-sitemap.js

      - name: Authenticate AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Upload sitemap.xml to S3
        run: |
          aws s3 cp public/sitemap.xml s3://vue-blog-frontend/sitemap.xml
