name: Frontend CI # action 명

on: # 이벤트 트리거
  push: # push event에 반응
   paths:
      - "frontend/**" # frontend의 변경이 있을 때
   branches: # github repository의 branch가 
      - main # main 일 경우만

jobs: 
  build: # GitHub-hosted runners env
    runs-on: ubuntu-latest # using Ubuntu 22.04 LTS
    defaults:
      run:
        working-directory: "frontend"
        
    steps:
      - name: git clone
        uses: actions/checkout@v3
      
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build page
        run: yarn build

      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install # will run `yarn install` command
  
      # - name: Build production bundle
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build # will run `yarn build` command

      - name: deploy # 배포
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://vue-blog-frontend
