name: Frontend Deploy # action 명

on: # 이벤트 트리거
  push: # push event에 반응
   paths:
      - "frontend/**" # frontend의 변경이 있을 때
   branches: # github repository의 branch가 
      - main # main 일 경우만

jobs: 
  deploy: # GitHub-hosted runners env
    runs-on: macos-latest # using MacOS

    defaults:
      run:
        working-directory: "frontend" # frontend 폴더에서 실행

    steps:
      - uses: actions/checkout@v3
      
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build page
        run: yarn build

      - name: remove 삭제
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_REGION }}'
        run: |
          aws s3 rm s3://vue-blog-frontend --recursive

      - name: deploy # 배포
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_REGION }}'
        run: |
          aws s3 cp --recursive dist s3://vue-blog-frontend
